FROM ghcr.io/puppeteer/puppeteer:latest

USER root
WORKDIR /home/pptruser

# Ensure Puppeteer downloads Chromium during npm install
ENV PUPPETEER_SKIP_DOWNLOAD=false
ENV PUPPETEER_PRODUCT=chrome

COPY package.json package-lock.json ./
RUN npm install

COPY ./server .

USER pptruser
EXPOSE 5000

CMD ["npm", "start"]