FROM node:18-alpine
WORKDIR /app
RUN apk add --no-cache chromium
COPY package.json ./
RUN npm install

# Copy only the backend server code into the container
COPY ./server .
EXPOSE 5000
ENV PUPPETEER_EXECUTABLE_PATH="/usr/bin/chromium-browser"
CMD ["npm", "start"]